# Generated by Django 4.1.4 on 2023-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_themes_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_themes',
            name='Theme_url',
            field=models.SlugField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
