# Generated by Django 4.1.4 on 2023-01-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_themes_theme_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_themes',
            name='Theme_category',
            field=models.CharField(choices=[('1', 'test')], default=0, max_length=255, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
