# Generated by Django 4.1.4 on 2023-01-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_themes_theme_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_themes',
            name='Theme_category',
            field=models.CharField(choices=[('Bday_Party', 'Bday_Party'), ('Bachelorette', 'Bachelorette'), ('Baby_Shower', 'Baby_Shower'), ('Corporate_party', 'Corporate_party')], max_length=255, verbose_name='Category'),
        ),
    ]
