# Generated by Django 4.1.4 on 2023-02-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_themes_theme_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBDHomepage_themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme_name', models.CharField(max_length=100)),
                ('Theme_price', models.IntegerField()),
                ('Theme_discount', models.IntegerField()),
                ('Theme_offer', models.BooleanField()),
                ('Theme_discription', models.TextField()),
                ('Theme_image', models.ImageField(upload_to='themePic')),
                ('Theme_url', models.SlugField(max_length=40)),
                ('Theme_category', models.CharField(choices=[('Bday_Party', 'Bday_Party'), ('Bachelorette', 'Bachelorette'), ('Baby_Shower', 'Baby_Shower'), ('Corporate_party', 'Corporate_party')], max_length=253, verbose_name='Category')),
                ('Theme_region', models.CharField(default='Bangalore', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FCDHomepage_themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme_name', models.CharField(max_length=100)),
                ('Theme_price', models.IntegerField()),
                ('Theme_discount', models.IntegerField()),
                ('Theme_offer', models.BooleanField()),
                ('Theme_discription', models.TextField()),
                ('Theme_image', models.ImageField(upload_to='themePic')),
                ('Theme_url', models.SlugField(max_length=40)),
                ('Theme_category', models.CharField(choices=[('Bday_Party', 'Bday_Party'), ('Bachelorette', 'Bachelorette'), ('Baby_Shower', 'Baby_Shower'), ('Corporate_party', 'Corporate_party')], max_length=253, verbose_name='Category')),
                ('Theme_region', models.CharField(default='Chennai', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FHHomepage_themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme_name', models.CharField(max_length=100)),
                ('Theme_price', models.IntegerField()),
                ('Theme_discount', models.IntegerField()),
                ('Theme_offer', models.BooleanField()),
                ('Theme_discription', models.TextField()),
                ('Theme_image', models.ImageField(upload_to='themePic')),
                ('Theme_url', models.SlugField(max_length=40)),
                ('Theme_category', models.CharField(choices=[('Bday_Party', 'Bday_Party'), ('Bachelorette', 'Bachelorette'), ('Baby_Shower', 'Baby_Shower'), ('Corporate_party', 'Corporate_party')], max_length=254, verbose_name='Category')),
                ('Theme_region', models.CharField(default='Hyderabad', max_length=100)),
            ],
        ),
       
    ]
