# Generated by Django 4.1.4 on 2023-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fbdhomepage_themes_fcdhomepage_themes_and_more'),]
